apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: default # Ensure this matches where your Grafana instance is running
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard # Uses Minikube's default hostpath provisioner
  resources:
    requests:
      storage: 2Gi # 2 Gigabytes is plenty for saving hundreds of dashboard templates
